language: node_js
node_js:
  - "8"
sudo: required
addons:
  chrome: stable
env:
  - NODE_OPTIONS=--max_old_space_size=4096
before_install:
  - npm i -g npm
install:
  - npm install
script: 
  - npm run lint
  - npm run test
cache:
  directories:
    - "node_modules"